services:
  app:
    image: kuuku123/studycafe-webflux-notification:latest
    ports:
      - "8082:8082" # Map container port to host
    environment:
      SPRING_PROFILES_ACTIVE: prod # Set the Spring profile

